### ISSUE TITLE
Frequent Crashes

### ISSUE THREAD

**Issue by RosalinaSama** [Maplespe/DWMBlurGlass#456]
**Describe the bug**
Multiple crashes requiring restart of the program, which have increased since the latest update

**To Reproduce**
> Steps to reproduce the behavior:
Usually occurs when a new Window opens or during a window being dragged to resize, but occasionally on other common tasks like right clicking a menu

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Pro 22H2 19045.5247
 > Software Version : 2.30

Screenshot of settings
![image](https://github.com/user-attachments/assets/359d589b-23de-4efa-9fe4-5908506da771)
![image](https://github.com/user-attachments/assets/771337ee-29fe-47fa-a730-cecb3cef6cd8)
I've tried turning on blur rendering optimization but it seems to turn off any time it crashes so I've given up turning it back on every time

**What other third-party software do you use:**
StartIsBack - For Windows 7 Taskbar
Aero10 Theme
Open Shell with menu glass
Windhawk Mods: Aerexplorer, Force Thick Frames, Aero Flyout Fix, UIFILE Override, Restore Windows 7 Caption Buttons

**Additional context**
Multiple crash dumps included, hope this helps: https://www.dropbox.com/scl/fi/dcq7xdw412mt0iee8f1fy/dumps.7z?rlkey=flqzlgmft00nsyo2hpedrkfu7&st=vtikbnmc&dl=0
Thanks for a great program either way, still very pleasant to look at even with these issues

**Comment by Maplespe** [comment]
An optimization in the new version should resolve the issue.

**Comment by RosalinaSama** [comment]
Unfortunately I'm still getting a lot of crashes on this new beta version, happy to upload some more logs if it helps! 
[dumps.zip](https://github.com/user-attachments/files/18420372/dumps.zip)

**Comment by Maplespe** [comment]
You don't seem to be using the latest beta.
There are 2 versions, you should use [DWMBlurGlass.2.3.1_Beta_x64.2024.1.8.zip](https://github.com/Maplespe/DWMBlurGlass/releases/download/2.3.1/DWMBlurGlass.2.3.1_Beta_x64.2024.1.8.zip).

**Comment by RosalinaSama** [comment]
> You don't seem to be using the latest beta. There are 2 versions, you should use [DWMBlurGlass.2.3.1_Beta_x64.2024.1.8.zip](https://github.com/Maplespe/DWMBlurGlass/releases/download/2.3.1/DWMBlurGlass.2.3.1_Beta_x64.2024.1.8.zip).

Just wanted to say, thank you so so much! This version is so much more stable and I don't think it's crashed at all since I've upgraded to this release
Appreciate all your work
