### ISSUE TITLE
Blur doesnt show on Mica windows in latest Windows 11 Beta

### ISSUE THREAD

**Issue by jimkoutso2008** [Maplespe/DWMBlurGlass#63]
This strangely enough doesn't happen with 1.0.2 so im going to stay on 1.0.2 for now

## Here are 2 apps that use Mica on **1.0.3**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/82086687/774971cb-429c-468a-89ac-fbf9c82cfc40)

## And the same ones on **1.0.2**
![image](https://github.com/Maplespe/DWMBlurGlass/assets/82086687/900b64bf-8f61-4fc0-bc54-0278c327a0dc)

Im using the exact same config in both images

**Comment by AquaHarp** [comment]
Same issue.
Note: I am using `ExplorerPatcher` , `Openshell 4.4.191` and `BasicThemer 2`

![屏幕截图 2024-01-27 232742](https://github.com/Maplespe/DWMBlurGlass/assets/25244319/581d9f50-1a42-4c66-814e-92219aa50af0)

![屏幕截图 2024-01-27 232848](https://github.com/Maplespe/DWMBlurGlass/assets/25244319/c7adede3-d551-451a-ba1c-3351cdc6a83f)

The exclusions of `BasicThemer 2`:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/25244319/8ae69f4f-5038-4541-ba1f-0a9162de418d)

**Comment by Arthurgamepraix** [comment]
The "Override DWMAPI mica effect" seems to break it, yet it still works  without it enabled.

**Comment by Maplespe** [comment]
Fixed in the latest version.

**Comment by AquaHarp** [comment]
> Fixed in the latest version.

the issues with `ExplorerPatcher` properties window and `Lenovo Legion Toolkit` are still exists.
![image](https://github.com/Maplespe/DWMBlurGlass/assets/25244319/d4b0bc8f-4481-4333-aeee-8e1a52515379)

**Comment by perfstr54** [comment]
There is a problem with displaying folder settings. The same problem is observed on previous versions
![Parameter](https://github.com/Maplespe/DWMBlurGlass/assets/158833519/8db8097a-84f5-4768-9436-25ef38ed368b)

**Comment by Maplespe** [comment]
Resolved in the new version.

**Comment by perfstr54** [comment]
Thanks, great job. Best wishes
